/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.DataManager;
import Model.ActualyWagonLocation;
import Model.WagonInTrain;
import Model.ActualyWagonLocation;
import Model.WagonOnStation;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import service.DBManager;

/**
 *
 * @author Bugy
 */
public class Reports extends javax.swing.JDialog {

    private DataManager DataManager;
    private Controller.Reports Reports;
    SimpleDateFormat Formater = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");

    /**
     * Creates new form Reports
     */
    public Reports(java.awt.Frame parent, boolean modal, DataManager dataManager, DBManager dbManager) {
        super(parent, modal);
        this.DataManager = dataManager;
        this.Reports = new Controller.Reports(dbManager);
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBoxWagonType1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxInService1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCopanyName1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxStationName1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jSpinnerDate1 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBoxStationName = new javax.swing.JComboBox<>();
        jComboBoxWagonType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxInService = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCopanyName = new javax.swing.JComboBox<>();
        jSpinnerDateFrom = new javax.swing.JSpinner();
        jSpinnerDateTo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBoxIdTrain = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxTrainType = new javax.swing.JComboBox<>();
        jComboBoxWagonType2 = new javax.swing.JComboBox<>();
        jSpinnerDate = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCopanyName2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxSelectWagon = new javax.swing.JComboBox<>();
        jBRefresh = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLocation = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jComboBoxWagonType1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxWagonType1MouseClicked(evt);
            }
        });
        jComboBoxWagonType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWagonType1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Typ vozňa");

        jLabel11.setText("V prevadzke");

        jComboBoxCopanyName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCopanyName1MouseClicked(evt);
            }
        });
        jComboBoxCopanyName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCopanyName1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Spoločnosť");

        jComboBoxStationName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxStationName1MouseClicked(evt);
            }
        });
        jComboBoxStationName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStationName1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Stanica");

        jSpinnerDate1.setModel(new javax.swing.SpinnerDateModel());

        jLabel16.setText("Dátum zosnímania");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 267, Short.MAX_VALUE))
                            .addComponent(jComboBoxStationName1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(204, 204, 204)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxWagonType1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxInService1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCopanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxStationName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCopanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxInService1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxWagonType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aktuálna poloha vozňov (1)", jPanel3);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBoxStationName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxStationNameMouseClicked(evt);
            }
        });
        jComboBoxStationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStationNameActionPerformed(evt);
            }
        });

        jComboBoxWagonType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxWagonTypeMouseClicked(evt);
            }
        });
        jComboBoxWagonType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWagonTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Stanica");

        jLabel2.setText("Typ vozňa");

        jLabel3.setText("V prevadzke");

        jLabel4.setText("Spoločnosť");

        jComboBoxCopanyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCopanyNameMouseClicked(evt);
            }
        });
        jComboBoxCopanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCopanyNameActionPerformed(evt);
            }
        });

        jSpinnerDateFrom.setModel(new javax.swing.SpinnerDateModel());

        jSpinnerDateTo.setModel(new javax.swing.SpinnerDateModel());

        jLabel5.setText("Dátum od");

        jLabel6.setText("Dátum do");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxStationName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxWagonType, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxInService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 317, Short.MAX_VALUE))
                            .addComponent(jComboBoxCopanyName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxStationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxWagonType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxInService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCopanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Zoznam vozňov na stanic (2)", jPanel2);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jComboBoxIdTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxIdTrainMouseClicked(evt);
            }
        });
        jComboBoxIdTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdTrainActionPerformed(evt);
            }
        });

        jLabel13.setText("Id a nazov vlaku");

        jLabel14.setText("Typ vlaku");

        jComboBoxTrainType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTrainTypeMouseClicked(evt);
            }
        });
        jComboBoxTrainType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrainTypeActionPerformed(evt);
            }
        });

        jComboBoxWagonType2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxWagonType2MouseClicked(evt);
            }
        });
        jComboBoxWagonType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWagonType2ActionPerformed(evt);
            }
        });

        jSpinnerDate.setModel(new javax.swing.SpinnerDateModel());

        jLabel7.setText("Typ vozňa");

        jLabel8.setText("Dátum");

        jComboBoxCopanyName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCopanyName2MouseClicked(evt);
            }
        });
        jComboBoxCopanyName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCopanyName2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Spoločnosť");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 154, Short.MAX_VALUE))
                            .addComponent(jComboBoxIdTrain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jComboBoxTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxWagonType2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCopanyName2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel7)
                                .addComponent(jLabel14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCopanyName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxWagonType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxIdTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addComponent(jButton4)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zoznam vozňov vo vlakoch (3)", jPanel4);

        jComboBoxSelectWagon.setMaximumRowCount(40);

        jBRefresh.setText("Refresh");
        jBRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefreshActionPerformed(evt);
            }
        });

        jTableLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTableLocation);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSelectWagon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBoxSelectWagon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBRefresh)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aktuálna poloha vozňa (4)", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Konkrétny vozeň aj histórrie (5)", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vyhľadávanie skupín vozňov (6)", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Štatistiky o vozňoch vo vlaku (7)", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Štatistiky o vozňoch na stanici (8)", jPanel9);

        jButton1.setText("Refresh");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Štatistíky pracovníkov (9)", jPanel1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Automatický zaevidované vozne (10)", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStationNameActionPerformed

    }//GEN-LAST:event_jComboBoxStationNameActionPerformed

    private void jComboBoxStationNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxStationNameMouseClicked

    }//GEN-LAST:event_jComboBoxStationNameMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setText("Refreshing...");
        jButton2.setEnabled(false);
        Thread t1 = new Thread(new Runnable() {
            public void run() {
                int i = 0;

                String stationName = String.valueOf(jComboBoxStationName.getSelectedItem());
                int stationId = DataManager.getStationId(stationName);
                String wagonType = String.valueOf(jComboBoxWagonType.getSelectedItem());
                String inService = String.valueOf(jComboBoxInService.getSelectedItem());
                String company = String.valueOf(jComboBoxCopanyName.getSelectedItem());
                SpinnerDateModel modelFrom = (SpinnerDateModel) jSpinnerDateFrom.getModel();
                SpinnerDateModel modelTo = (SpinnerDateModel) jSpinnerDateTo.getModel();

                List<WagonOnStation> wagons = Reports.getWagonsOnStation(stationId, wagonType, inService, modelFrom.getDate(), modelTo.getDate(), company);
                Object[][] o = new Object[wagons.size()][4];
                for (WagonOnStation wagon : wagons) {
                    o[i][0] = wagon.getIdWagon();
                    o[i][1] = wagon.getType();
                    o[i][2] = wagon.getInService();
                    o[i][3] = wagon.getCompany();
                    i++;
                }
                DefaultTableModel d = new DefaultTableModel(o, new Object[]{"Id vlaku", "Typ vozňa", "V prevádzke", "Spoločnosť"});
                jTable2.setModel(d);
                jButton2.setText("Refresh");
                jButton2.setEnabled(true);
            }
        });
        t1.start();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton3.setText("Refreshing...");
        jButton3.setEnabled(false);
        Thread t1 = new Thread(new Runnable() {
            public void run() {
                int i = 0;

                String comboStation = String.valueOf(jComboBoxStationName1.getSelectedItem());
                if (!Reports.isNullOrEmpty(comboStation)) {
                    int idStation = DataManager.getStationId(String.valueOf(jComboBoxStationName1.getSelectedItem()));
                    comboStation = Integer.toString(idStation);
                }

                String wagonType = String.valueOf(jComboBoxWagonType1.getSelectedItem());
                String company = String.valueOf(jComboBoxCopanyName1.getSelectedItem());
                String inService = String.valueOf(jComboBoxInService1.getSelectedItem());
                SpinnerDateModel modelDate = (SpinnerDateModel) jSpinnerDate1.getModel();

                List<ActualyWagonLocation> wagons = Reports.getCurrentWagonsLocation(comboStation, wagonType, inService, modelDate.getDate(), company);
                Object[][] o = new Object[wagons.size()][9];
                for (ActualyWagonLocation wagon : wagons) {
                    o[i][0] = wagon.getStationName();
                    o[i][1] = wagon.getWagonType();
                    o[i][2] = wagon.getInService();
                    o[i][3] = wagon.getCompany();
                    o[i][4] = wagon.getIDWagon();
                    o[i][5] = wagon.getLatitude();
                    o[i][6] = wagon.getLongitude();
                    o[i][7] = Formater.format(wagon.getDateFrom());
                    o[i][8] = wagon.getDateTo() == null ? null : Formater.format(wagon.getDateTo());
                    i++;
                }
                DefaultTableModel d = new DefaultTableModel(o, new Object[]{"Stanica", "Typ vozňa", "V prevádzke", "Spoločnosť", "Id vozňa", "Zem šírka", "Zem dĺžka", "Dátum snímania od", "Dátum snímania do"});
                jTable3.setModel(d);
                jButton3.setText("Refresh");
                jButton3.setEnabled(true);
            }
        });
        t1.start();
    }

    private void jComboBoxWagonType1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxWagonType1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxCopanyName1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxCopanyName1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxStationName1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxStationName1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBoxWagonTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxWagonTypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWagonTypeMouseClicked

    private void jComboBoxWagonTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWagonTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWagonTypeActionPerformed

    private void jComboBoxCopanyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCopanyNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCopanyNameMouseClicked

    private void jComboBoxCopanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCopanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCopanyNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setText("Refreshing...");
        jButton4.setEnabled(false);
        Thread t1 = new Thread(new Runnable() {
            public void run() {
                int i = 0;

                String idAndNameTrain = String.valueOf(jComboBoxIdTrain.getSelectedItem());
                String idTrain = idAndNameTrain.split("-")[0];
                String trainType = String.valueOf(jComboBoxTrainType.getSelectedItem());
                String wagonType = String.valueOf(jComboBoxWagonType2.getSelectedItem());
                String company = String.valueOf(jComboBoxCopanyName2.getSelectedItem());
                SpinnerDateModel modelDate = (SpinnerDateModel) jSpinnerDate.getModel();

                List<WagonInTrain> wagons = Reports.getWagonsInTrain(Integer.parseInt(idTrain), trainType, wagonType, modelDate.getDate(), company);
                Object[][] o = new Object[wagons.size()][8];
                for (WagonInTrain wagon : wagons) {
                    o[i][0] = wagon.getIdTrain();
                    o[i][1] = wagon.getTrainName();
                    o[i][2] = wagon.getTrainType();
                    o[i][3] = wagon.getIdWagon();
                    o[i][4] = wagon.getWagonType();
                    o[i][5] = wagon.getCompany();
                    o[i][6] = Formater.format(wagon.getDateFrom());
                    o[i][7] = wagon.getDateTo() == null ? null : Formater.format(wagon.getDateTo());
                    i++;
                }
                DefaultTableModel d = new DefaultTableModel(o, new Object[]{"Id vlaku", " Názov vlaku", "Typ Vlaku", "Id vozňa", "Typ vozňa", "Spoločnosť", "Dátum od", "Dátum do"});
                jTable4.setModel(d);
                jButton4.setText("Refresh");
                jButton4.setEnabled(true);
            }
        });
        t1.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxIdTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxIdTrainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIdTrainMouseClicked

    private void jComboBoxIdTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIdTrainActionPerformed

    private void jComboBoxTrainTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTrainTypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrainTypeMouseClicked

    private void jComboBoxTrainTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrainTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrainTypeActionPerformed

    private void jComboBoxWagonType2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxWagonType2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWagonType2MouseClicked

    private void jComboBoxWagonType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWagonType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWagonType2ActionPerformed

    private void jComboBoxCopanyName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCopanyName2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCopanyName2MouseClicked

    private void jComboBoxCopanyName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCopanyName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCopanyName2ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jBRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefreshActionPerformed
        // TODO add your handling code here:
        jBRefresh.setText("Refreshing...");
        jBRefresh.setEnabled(false);
        Thread t1 = new Thread(new Runnable() {
            public void run() {
                int i = 0;

                String idWagon = String.valueOf(jComboBoxSelectWagon.getSelectedItem());
                List<ActualyWagonLocation> actWagons = Reports.getWagonLocation(idWagon);
                Object[][] o = new Object[actWagons.size()][2];
                for (ActualyWagonLocation wagon : actWagons) {
                    o[i][0] = wagon.getLongitude();
                    o[i][1] = wagon.getLatitude();
                    i++;
                }
                DefaultTableModel d = new DefaultTableModel(o, new Object[]{" zem dlzka", "zem sirka"});
                jTableLocation.setModel(d);
                jBRefresh.setText("Refresh");
                jBRefresh.setEnabled(true);
            }
        });
        t1.start();
    }//GEN-LAST:event_jBRefreshActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
         Thread t1 = new Thread(new Runnable() {
            public void run() {
        List<String> stations = DataManager.getStationNames();
        jComboBoxStationName.setModel(new DefaultComboBoxModel(stations.toArray()));

        List<String> stations2 = new ArrayList<>(Arrays.asList(""));
        stations2.addAll(stations);
        jComboBoxStationName1.setModel(new DefaultComboBoxModel(stations2.toArray()));

        List<String> wagonTypes = new ArrayList<>(Arrays.asList(""));
        wagonTypes.addAll(DataManager.getWagonTypes());
        jComboBoxWagonType.setModel(new DefaultComboBoxModel(wagonTypes.toArray()));
        jComboBoxWagonType1.setModel(new DefaultComboBoxModel(wagonTypes.toArray()));
        jComboBoxWagonType2.setModel(new DefaultComboBoxModel(wagonTypes.toArray()));

        List<String> inServiceLs = new ArrayList<>(Arrays.asList("", "N", "Y"));
        jComboBoxInService.setModel(new DefaultComboBoxModel(inServiceLs.toArray()));
        jComboBoxInService1.setModel(new DefaultComboBoxModel(inServiceLs.toArray()));

        List<String> companyNames = new ArrayList<>(Arrays.asList(""));
        companyNames.addAll(DataManager.getCompanyNames());
        jComboBoxCopanyName.setModel(new DefaultComboBoxModel(companyNames.toArray()));
        jComboBoxCopanyName1.setModel(new DefaultComboBoxModel(companyNames.toArray()));
        jComboBoxCopanyName2.setModel(new DefaultComboBoxModel(companyNames.toArray()));

        List<String> trainIds = DataManager.getTrainIds();
        jComboBoxIdTrain.setModel(new DefaultComboBoxModel(trainIds.toArray()));

        List<String> trainTypes = new ArrayList<>(Arrays.asList(""));
        trainTypes.addAll(DataManager.getTrainTypes());
        jComboBoxTrainType.setModel(new DefaultComboBoxModel(trainTypes.toArray()));

        List<String> idWagons = DataManager.getWagonId();
        jComboBoxSelectWagon.setModel(new DefaultComboBoxModel(idWagons.toArray()));
            }
        });
        t1.start();      
    }//GEN-LAST:event_jTabbedPane1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxCopanyName;
    private javax.swing.JComboBox<String> jComboBoxCopanyName1;
    private javax.swing.JComboBox<String> jComboBoxCopanyName2;
    private javax.swing.JComboBox<String> jComboBoxIdTrain;
    private javax.swing.JComboBox<String> jComboBoxInService;
    private javax.swing.JComboBox<String> jComboBoxInService1;
    private javax.swing.JComboBox<String> jComboBoxSelectWagon;
    private javax.swing.JComboBox<String> jComboBoxStationName;
    private javax.swing.JComboBox<String> jComboBoxStationName1;
    private javax.swing.JComboBox<String> jComboBoxTrainType;
    private javax.swing.JComboBox<String> jComboBoxWagonType;
    private javax.swing.JComboBox<String> jComboBoxWagonType1;
    private javax.swing.JComboBox<String> jComboBoxWagonType2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinnerDate;
    private javax.swing.JSpinner jSpinnerDate1;
    private javax.swing.JSpinner jSpinnerDateFrom;
    private javax.swing.JSpinner jSpinnerDateTo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTableLocation;
    // End of variables declaration//GEN-END:variables
}
